# 실행 모드: train 또는 generate
mode: train

# 데이터 설정
data:
  train_data_path: "amorphous_Si.extxyz"  # 학습 데이터 경로
#  val_data_path: "data/val_structures.extxyz"      # 검증 데이터 경로 (선택사항)
  dataset_save_path: "processed_dataset.pt"   # 처리된 데이터셋 저장 경로 (선택사항)
  graph_cutoff: 5.0          # 그래프 구성 시 cutoff distance (Å)
  r_max: 10.0                # RDF 계산 최대 거리 (Å)
  n_bins: 100                # RDF 히스토그램 bin 개수
  normalize_rdf: true        # RDF 정규화 여부

# 모델 설정
model:
  node_dim: 3                # 노드 특징 차원 (x, y, z 좌표)
  edge_dim: 1                # 에지 특징 차원 (거리)
  hidden_dim: 128            # 은닉층 차원
  num_layers: 6              # 그래프 컨볼루션 레이어 수
  condition_dim: 100         # 조건(RDF) 특징 차원

# Diffusion 프로세스 설정
diffusion:
  beta_start: 0.0001           # β 시작값
  beta_end: 0.02             # β 종료값
  num_timesteps: 1000        # Diffusion 스텝 수
  schedule: "linear"         # β 스케줄 (linear 또는 cosine)

# 학습 설정
training:
  device: "cpu"             # 사용할 디바이스 (cuda 또는 cpu)
  batch_size: 32             # 배치 크기
  num_epochs: 1000           # 총 에폭 수
  learning_rate: 1e-4        # 학습률
  weight_decay: 1e-6         # 가중치 감쇠
  output_dir: "outputs"      # 출력 디렉토리
  checkpoint_dir: "outputs/checkpoints"  # 체크포인트 저장 디렉토리
  log_dir: "outputs/logs"    # 로그 저장 디렉토리
  checkpoint_interval: 10    # 체크포인트 저장 간격 (에폭 수)
  log_interval: 10           # 로그 출력 간격 (배치 수)
  resume_from_checkpoint: null  # 재개할 체크포인트 경로 (없으면 null)

# 생성 설정 (generate 모드에서 사용)
generation:
  lattice_vector: [10.0, 10.0, 10.0]  # 격자 벡터 [a, b, c] (Å)
  density: 2.2                         # 밀도 (g/cm³)
  chemical_formula: "SiO2"             # 화학식
  num_atoms: 90                        # 원자 수
  target_rdf: "target_rdf.npy"         # 목표 RDF 파일 경로 또는 배열
  num_structures: 5                    # 생성할 구조 개수
  output_path: "generated_structures.extxyz"  # 생성된 구조 출력 경로
